version: '3.7'

x-db-envs: &db-envs
  POSTGRES_USER: ${DB_USER}
  POSTGRES_PASSWORD: ${DB_PASSWORD}
  POSTGRES_DB: ${DB_NAME}
  DATABASE_HOST: ${DB_HOST}

services:
  app:
    container_name: upper_tweet
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - '8080:8080'
    restart: on-failure
    volumes:
      - .:/api:delegated
    networks:
      - fiinet

  db-postgres:
    image: postgres:latest
    container_name: db_postgres
    environment:
      <<: *db-envs
    ports:
      - '5432:5432'
    volumes:
      - ./database_postgres:/var/lib/postgresql/data
    networks:
      - fiinet

  migrate:
    image: migrate/migrate
    networks:
      - fiinet
    volumes:
      - ./migrations:/migrations
    command: version
    depends_on:
      - db-postgres

networks:
  fiinet:
    driver: bridge
