version: '3.7'

x-db-envs: &db-envs
  POSTGRES_USER: ${TEST_DB_USER}
  POSTGRES_PASSWORD: ${TEST_DB_PASSWORD}
  POSTGRES_DB: ${TEST_DB_NAME}
  DATABASE_HOST: ${TEST_DB_HOST}

services:
  app-test:
    container_name: upper_tweet_test
    build:
      context: .
      dockerfile: ./Dockerfile.test
    ports:
      - '8080:8080'
    restart: on-failure
    depends_on:
      - db-test-postgres
    volumes:
      - .:/app:delegated
    networks:
      - fiinet-test
      
  db-test-postgres:
    image: postgres:latest
    container_name: db_postgres_test
    environment:
      <<: *db-envs
    ports:
      - '5432:5432'
    volumes:
      - ./database_test_postgres:/var/lib/postgresql/data
    networks:
      - fiinet-test

#  migrate:
#    image: migrate/migrate
#    networks:
#      - fiinet-test
#    volumes:
#      - ./migrations:/migrations
#    command: version
#    depends_on:
#      - db-test-postgres

networks:
  fiinet-test:
    driver: bridge
